version: "3.0"
services:
  run:
    build: .
  run-gunicorn:
    build:
      dockerfile: Dockerfile.gunicorn
      context: .
    environment:
      PORT: 8081
    ports:
      - "8081:8081"
  cache:
    image: varnish
    volumes:
    - ./varnish:/etc/varnish:z
  test:
    image: python:3.8
    volumes:
      - .:/code
    working_dir: /code
    command:
      - bash
      - -c
      - pip install tox; tox
